version: "3.8"
services:
  rocket-django:
    container_name: appstripe
    restart: always
    build: .
    networks:
      - db_network
      - web_network
  nginx:
    container_name: nginx
    restart: always
    image: "nginx:alpine-slim"
    ports:
      - "5085:5085"
    volumes:
      - ./nginx:/etc/nginx/conf.d
    networks:
      - web_network
    depends_on:
      - rocket-django
networks:
  db_network:
    driver: bridge
  web_network:
    driver: bridge
